### ISSUE TITLE
[BUG] Visual issues with shield orientation when blocking, elven armor, female armor color tones, and female body

### ISSUE THREAD

**Issue by TestTubePuppy** [Althro/Tinvaak2#37] opened 2022-03-29 02:10 UTC
**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak2/files/8367376/modlist.txt)

**Describe the bug**
Various visual issues. Described separately ahead of each screenshot.

**To Reproduce**

1. Enter `coc qasmoke` in the console and try on armors from the "All Standard Armors" chest.
2. Create a female character to see female-specific issues.

**Expected behavior**
Upright shields, visible elven armor, matching color tones on female helms/armors, breasts lining up with bra on unclothed female body.

**Screenshots**
1. Shields appear to be held sideways when blocking. Affects both male and female characters, across many (all?) shields.

![male_blocking](https://user-images.githubusercontent.com/102565812/160517119-b0180214-fa19-48ba-8e84-7c5c20909f88.png)
![female_blocking](https://user-images.githubusercontent.com/102565812/160517128-96c4650b-7a83-4a6b-b7dd-68310a7f4ae9.png)

2. Elven Armor and Elven Light Armor are invisible. Affects both male and female characteres.

![female_invisible_armor](https://user-images.githubusercontent.com/102565812/160517444-fd218cc4-c71a-4618-9ce2-9e79ccf984af.png)
![male_invisible_armor](https://user-images.githubusercontent.com/102565812/160517446-ce0e6fb3-61ec-413a-842d-4145f6264442.png)

3. Unclothed female body looks strange (shadows? breasts don't line up with bra?)

![female_body_issue](https://user-images.githubusercontent.com/102565812/160517631-b1fb3917-f235-4ad8-9eae-f589a2333eba.png)

4. Various female armors have a mismatch between helm and body color tones/luster (eg., Glass, Orcish, Ancient Shrouded Armor, more?)

![glass_armor](https://user-images.githubusercontent.com/102565812/160518201-cce41dd0-a59e-499d-9232-fbe03fb4cbf3.png)
![orcish_armor](https://user-images.githubusercontent.com/102565812/160518217-b348ddff-2a8b-4018-bd2e-0c2c716bd8b7.png)
![ancient_shrouded_armor](https://user-images.githubusercontent.com/102565812/160518219-622df9eb-d886-4ebe-a34d-e00945cf8f4a.png)

**Modlist version**

v2.2.0

**Did you add any additional mods?**

Just the ultrawide (21:9) mods recommended in the official guide.

**Comment by bertherbert** [comment] 2022-03-29 23:44
I'm having the same issue with the elven armor. Only mod I've installed is the ultra wide fix too.

**Comment by Para0x** [comment] 2022-03-29 23:56
**Elven Armor Bug:**
The elven armor issue is under investigation, but we're not quite sure what the cause is yet.

**Shield Orientation:**
This is an intended animation from the Elder Souls Collection. The author never corrected the shield orientation in the hkx to account for all different types of shields.

**Comment by Teldram** [comment] 2022-03-31 10:24
Here's what I did to fix it in my very 11ruled list: 
[DIY Tale of Two Mers FIX.zip](https://github.com/Althro/Tinvaak2/files/8388388/DIY.Tale.of.Two.Mers.FIX.zip)

I tested it very quickly and some thalmor soldiers that had an invisible cuirass before were fixed
![enb2022_3_30_04_04_09](https://user-images.githubusercontent.com/37117951/161034125-ec691e75-9325-47ed-9f60-92f91917bdc8.jpg)

**Comment by Althro** [comment] 2022-04-02 13:55
The armor issue is fixed in 2.3 as should the bodyslide issues. Thanks @Teldram for the fix 👯‍♂️

**Closed by Althro** 2022-04-02 13:55 UTC
Labels: bug
